In [2]:
import torch
from torchvision.io.image import read_image
import matplotlib.pyplot as plt

In [2]:
number = torch.rand([1, 3, 128, 128])

In [ ]:
bernoulli_dist = torch.distributions.Bernoulli(0.5)
bernoulli_dist.sample()

In [ ]:
dirichlet_dist = torch.distributions.Dirichlet(torch.tensor([2.0, 2.0]))
samples = dirichlet_dist.sample((1000,))
# plt.hist2d(samples[:,0], samples[:,1])
plt.hist2d(samples[:, 0], samples[:, 1])

In [52]:
torch.digamma(torch.tensor(100000)) - torch.digamma(torch.tensor([5, 10]))

tensor([10.0068,  9.2612])

In [208]:
def cross_entropy_dirichlet(prediction: torch.Tensor, target: torch.Tensor):
    alpha = prediction + 1
    diriclet_strength = alpha.sum(dim=1, keepdim=True)
    return target * (torch.digamma(diriclet_strength) - torch.digamma(alpha))


def KL_divergence_dirichlet(prediction: torch.Tensor, target: torch.Tensor):
    alpha = prediction + 1
    n_class = torch.tensor(prediction.size(1))
    approx_alpha = target + (1 - target) * alpha

    first_term = torch.lgamma(approx_alpha.sum(dim=1))
    first_term -= torch.lgamma(n_class) + torch.lgamma(approx_alpha).sum(dim=1)
    second_term = (
        (approx_alpha - 1)
        * (
            torch.digamma(approx_alpha)
            - torch.digamma(approx_alpha.sum(dim=1, keepdim=True))
        )
    ).sum(dim=1)
    print(approx_alpha.prod(dim=1))
    return first_term + second_term


def overall_loss(
    prediction: torch.Tensor,
    target: torch.Tensor,
    lambda_t: torch.Tensor,
):
    return cross_entropy_dirichlet(
        prediction, target
    ) + lambda_t * KL_divergence_dirichlet(
        prediction,
        target,
    )


prediction = torch.tensor([[1000, 1000, 20]])
target = torch.tensor([[1, 0, 0]])
overall_loss(prediction, target, torch.tensor(1)).sum()

tensor([21021])


tensor(28.4607)

In [ ]:
torch.digamma()

In [228]:
prediction = torch.rand([2, 3, 2, 2]) * 10
target = torch.zeros([2, 3, 2, 2])

n_class = torch.tensor(prediction.size(1))
approx_alpha = target + (1 - target) * prediction
first_term = torch.log(
    gamma(approx_alpha.sum(dim=1)) / (gamma(n_class) * gamma(approx_alpha).prod(dim=1))
)

second_term = (
    (approx_alpha - 1)
    * (
        torch.digamma(approx_alpha)
        - torch.digamma(approx_alpha.sum(dim=1, keepdim=True))
    )
).sum(dim=1)

print(first_term)
# print(second_term)
# print(first_term + second_term)
# KL_divergence_dirichlet(prediction, target).mean()

tensor([[[ 9.1247, 23.0307],
         [16.1171, 16.5673]],

        [[ 9.4902, 14.7805],
         [14.5074,  9.5673]]])


In [ ]:
beta_dist = torch.distributions.Beta(2 + 1, 3 + 1)
print(beta_dist.mean)

beta_dist = torch.distributions.Beta(3 + 1, 2 + 1)
print(beta_dist.mean)

beta_dist = torch.distributions.Beta(4 + 1, 1 + 1)
print(beta_dist.mean)

In [ ]:
torch.digamma(torch.tensor(1.6))